# -*- coding: utf-8 -*-
"""PowerFlowDNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y8RS8q-coGOKjl1QHlHuElqOPVvWPHVU
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf # This is the standard way to import TensorFlow
import joblib
import mlflow

try:
    inputs_df = pd.read_csv("combined_power_flow_inputs.csv")
    outputs_df = pd.read_csv("combined_power_flow_outputs.csv")
    print("Data loaded successfully.")
    print(f"Inputs DataFrame shape: {inputs_df.shape}")
    print(f"Outputs DataFrame shape: {outputs_df.shape}")
except FileNotFoundError:
    print("Error: Make sure 'combined_power_flow_inputs.csv' and 'combined_power_flow_outputs.csv' are in the same directory as this script.")
    print("Please run the power generation script first to create these files.")
    exit() # Exit if files are not found, as we cannot proceed without them

# --- 2. Identify and Remove Constant Columns BEFORE SCALING ---
print("\n--- Identifying and Removing Constant Columns ---")

# Creating ML FLow Experiment (for experiment tracking)
mlflow.set_experiment("MLflow for PowerFlow DNN")

# Find constant columns in inputs_df
constant_input_cols = [col for col in inputs_df.columns if inputs_df[col].nunique() == 1]
if constant_input_cols:
    print(f"Found constant input columns: {constant_input_cols}. Removing them.")
    inputs_df = inputs_df.drop(columns=constant_input_cols)
else:
    print("No constant input columns found.")

# Find constant columns in outputs_df
constant_output_cols = [col for col in outputs_df.columns if outputs_df[col].nunique() == 1]
if constant_output_cols:
    print(f"Found constant output columns: {constant_output_cols}. Removing them.")
    outputs_df = outputs_df.drop(columns=constant_output_cols)
else:
    print("No constant output columns found.")

print(f"New Inputs DataFrame shape after constant column removal: {inputs_df.shape}")
print(f"New Outputs DataFrame shape after constant column removal: {outputs_df.shape}")

# --- 3. Data Preprocessing (Scaling) ---
print("\n--- Starting Data Preprocessing (Scaling) ---")

inputs_df.fillna(0, inplace=True)

input_scaler = StandardScaler()
scaled_inputs_np = input_scaler.fit_transform(inputs_df)
scaled_inputs_df = pd.DataFrame(scaled_inputs_np, columns=inputs_df.columns)

output_scaler = StandardScaler()
scaled_outputs_np = output_scaler.fit_transform(outputs_df)
scaled_outputs_df = pd.DataFrame(scaled_outputs_np, columns=outputs_df.columns)

print(scaled_inputs_df.describe)
print(scaled_outputs_df.describe)

# --- Diagnostic Print for Scaled Outputs and Inputs (CONFIRMATION) ---
print("\n--- Descriptive Statistics for Scaled Outputs DataFrame (Full - After Cleanup) ---")
print(scaled_outputs_df.describe())
print("\nChecking for NaN/Inf in Scaled Outputs (After Cleanup):")
print("Any NaN in scaled outputs:", scaled_outputs_df.isnull().any().any())
print("Any Inf in scaled outputs:", scaled_outputs_df.isin([np.inf, -np.inf]).any().any())

print("\n--- Descriptive Statistics for Scaled Inputs DataFrame (Full - After Cleanup) ---")
print(scaled_inputs_df.describe())
print("\nChecking for NaN/Inf in Scaled Inputs (After Cleanup):")
print("Any NaN in scaled inputs:", scaled_inputs_df.isnull().any().any())
print("Any Inf in scaled inputs:", scaled_inputs_df.isin([np.inf, -np.inf]).any().any())
# --- End Diagnostic Print ---

X = scaled_inputs_df
y = scaled_outputs_df

# Fix: Ensure X and y have the same number of samples (rows)
# This assumes that the first 'len(y)' samples of X correspond to the samples in y.
if len(X) > len(y):
    print(f"Warning: X has more samples ({len(X)}) than y ({len(y)}). Truncating X to match y's length.")
    X = X.iloc[:len(y)]
elif len(y) > len(X):
    print(f"Warning: y has more samples ({len(y)}) than X ({len(X)}). Truncating y to match X's length.")
    y = y.iloc[:len(X)]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("\n--- Data Split Summary ---")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

input_dim = X_train.shape[1]
output_dim = y_train.shape[1]

mlflow.tensorflow.autolog()
#4 metrics while training: loss, MAE, val loss and val mae -  val loss imp for overfitting underffiting detection
# Corrected Model Definition with CORRECT Batch Normalization placement
model = tf.keras.models.Sequential([
    # First Hidden Layer
    tf.keras.layers.Dense(
        units=512,
        input_shape=(input_dim,),
        activation=None, # <<< IMPORTANT: REMOVE 'relu' HERE
        name='dense_hidden_1'
    ),
    tf.keras.layers.BatchNormalization(name='bn_1'),
    tf.keras.layers.Activation('relu', name='relu_1'),

    # Second Hidden Layer
    tf.keras.layers.Dense(
        units=256,
        activation=None, # <<< IMPORTANT: REMOVE 'relu' HERE
        name='dense_hidden_2'
    ),
    tf.keras.layers.BatchNormalization(name='bn_2'),
    tf.keras.layers.Activation('relu', name='relu_2'),

    # Third Hidden Layer
    tf.keras.layers.Dense(
        units=128,
        activation=None, # <<< IMPORTANT: REMOVE 'relu' HERE
        name='dense_hidden_3'
    ),
    tf.keras.layers.BatchNormalization(name='bn_3'),
    tf.keras.layers.Activation('relu', name='relu_3'),

    # Output Layer (linear activation is correct here)
    tf.keras.layers.Dense(
        units=output_dim,
        activation='linear',
        name='output_layer'
    )
])

# Keep the learning rate at 0.0001 (or 0.0005 if that was the one that gave NaN)
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001), # Assuming this is your current LR
              loss=tf.keras.losses.MeanSquaredError(),
              metrics=['mae'])
model.summary()
# training the model
print("\n--- Training the Neural Network Model ---")
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.1, verbose=1)

print("\n--- Evaluating the Neural Network Model on Test Data ---")
test_loss, test_mae = model.evaluate(X_test, y_test, verbose=0) # Changed verbose to 0 for cleaner evaluation output

print(f"\nTest Set Results (on Scaled Data):")
print(f"  Test Loss (Mean Squared Error): {test_loss:.4f}")
print(f"  Test Mean Absolute Error: {test_mae:.4f}")

# predict test data
print("\n--- Making Predictions and Viewing in Original Scale ---")
predictions = model.predict(X_test.head(5))

# inverse transform
inv_predict = output_scaler.inverse_transform(predictions)
y_test_inv = output_scaler.inverse_transform(y_test.head(5))

print("\nOriginal Scale Actual Outputs (First 5 samples - rounded for readability):")
print(pd.DataFrame(y_test_inv, columns=y_test.columns).round(3))

print("\nOriginal Scale Predicted Outputs (First 5 samples - rounded for readability):")
print(pd.DataFrame(inv_predict, columns=y_test.columns).round(3))

print("\n--- Neural Network Training Pipeline Completed ---")

model_save_path = 'power_flow_nn_model.h5' # .h5 extension indicates HDF5 format
model.save(model_save_path)
print(f"Keras model saved to: {model_save_path}")

# Save the input scaler
input_scaler_path = 'input_scaler.pkl' # .pkl is a common extension for pickle/joblib files
joblib.dump(input_scaler, input_scaler_path)
print(f"Input scaler saved to: {input_scaler_path}")

# Save the output scaler
output_scaler_path = 'output_scaler.pkl'
joblib.dump(output_scaler, output_scaler_path)
print(f"Output scaler saved to: {output_scaler_path}")